/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import Controle.IVeiculoControle;
import Controle.VeiculoControle;
import Modelos.Veiculo;
import Persistencia.IVeiculoDao;
import Persistencia.VeiculoDao;
import Conection.DatabaseConnection;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import Renderizador.RendererIcon; 


public class TelaDosVeiculos extends javax.swing.JFrame {
    private IVeiculoControle veiculoControle;
    
    
    public TelaDosVeiculos() {
        initComponents();
        setExtendedState(TelaDosModelos.MAXIMIZED_BOTH);
        preencherComboBoxMarcasModelos();
        
        // Inicia a Tabela  atualizada.
        IVeiculoDao veiculoDao = new VeiculoDao();
        DefaultTableModel tableModel = (DefaultTableModel) tabelaVeiculos.getModel();

        // Limpar dados existentes na tabela
        tableModel.setRowCount(0);

        // Obter lista de marcas do banco de dados
        List<Veiculo> veiculos = veiculoDao.listarVeiculos();

        // Preencher tabela com os dados das marcas
        for (Veiculo veiculo : veiculos) {
            Object[] rowData = {veiculo.getId(), veiculo.getModelo(), veiculo.getMarca(), veiculo.getUrl()};
            tableModel.addRow(rowData);
        }
    }
    
    
private void preencherComboBoxMarcasModelos() {
    try {
        Connection connection = DatabaseConnection.getConnection();
        
        //////////// Combobox Marcas
        PreparedStatement stmt = connection.prepareStatement("SELECT marcas FROM tabelademarcas");
        ResultSet rs = stmt.executeQuery();

        List<String> marcas = new ArrayList<>();
        while (rs.next()) {
            marcas.add(rs.getString("marcas"));
        }
        
        // Adicionar item vazio como primeiro elemento da lista de marcas
        marcas.add(0, "");

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(marcas.toArray(new String[0]));
        JCBX_Marca.setModel(comboBoxModel);

        rs.close();
        stmt.close();

        
        //////////// Combobox Modelos
        PreparedStatement stm = connection.prepareStatement("SELECT modelos FROM tabelademodelos");
        ResultSet rsa = stm.executeQuery();

        List<String> modelos = new ArrayList<>();
        while (rsa.next()) {
            modelos.add(rsa.getString("modelos"));
        }
        
        // Adicionar item vazio como primeiro elemento da lista de modelos
        modelos.add(0, "");

        DefaultComboBoxModel<String> comboBoxMode = new DefaultComboBoxModel<>(modelos.toArray(new String[0]));
        JCBX_Modelo.setModel(comboBoxMode);

        rsa.close();
        stm.close();
        connection.close();

    } 
    catch (SQLException e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Btn_Incluir = new javax.swing.JButton();
        Btn_Alterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_URL = new javax.swing.JTextField();
        JCBX_Marca = new javax.swing.JComboBox<>();
        JCBX_Modelo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        Panel_Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        Btn_Add = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuMarcas = new javax.swing.JMenu();
        MenuModelos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tela de Cadastro de Veiculos"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados dos Veiculos"));

        Btn_Incluir.setText("Incluir");
        Btn_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IncluirActionPerformed(evt);
            }
        });

        Btn_Alterar.setText("Alterar");
        Btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlterarActionPerformed(evt);
            }
        });

        jLabel2.setText("URL :");

        jLabel3.setText("Marca :");

        jLabel4.setText("Modelo :");

        JCBX_Marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCBX_MarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JCBX_MarcaFocusLost(evt);
            }
        });

        JCBX_Modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JCBX_ModeloFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Incluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Alterar)
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JCBX_Marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCBX_Modelo, 0, 151, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JCBX_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JCBX_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 210, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Incluir)
                    .addComponent(Btn_Alterar))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto do Veiculo"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Panel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Panel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "MARCA", "MODELO", "URL"
            }
        ));
        tabelaVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVeiculos);

        Btn_Add.setText("Add");
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Add)
                                .addGap(110, 110, 110))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Add))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        MenuMarcas.setText("Tela de Marcas");
        jMenu1.add(MenuMarcas);

        MenuModelos.setText("Tela de Modelos");
        jMenu1.add(MenuModelos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IncluirActionPerformed
         if (!Txt_URL.getText().equals("")){
            String nomeMarca = (String) JCBX_Marca.getSelectedItem();
            String nomeModelo = (String) JCBX_Modelo.getSelectedItem();
            String url = Txt_URL.getText();

            IVeiculoDao veiculoDao = new VeiculoDao();
            IVeiculoControle veiculoControle = new VeiculoControle(veiculoDao, (DefaultTableModel) tabelaVeiculos.getModel());
            veiculoControle.adicionarVeiculo(nomeMarca, nomeModelo ,url);
        }
        else{
            JOptionPane.showMessageDialog(null, "Campos vazios !");
        }
    }//GEN-LAST:event_Btn_IncluirActionPerformed

    private void Btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlterarActionPerformed
        if (!Txt_URL.getText().equals("")){
            String nomeMarca = (String) JCBX_Marca.getSelectedItem();
            String nomeModelo = (String) JCBX_Modelo.getSelectedItem();
            String url = Txt_URL.getText();

            int selectedRow = tabelaVeiculos.getSelectedRow();
            if (selectedRow != -1) {
                int idMarca = (int) tabelaVeiculos.getValueAt(selectedRow, 0);
                IVeiculoControle atualiza = new VeiculoControle(new VeiculoDao(), (DefaultTableModel) tabelaVeiculos.getModel());
                atualiza.atualizarVeiculo(idMarca, nomeMarca, nomeModelo, url);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Campos vazios !");
        }
    }//GEN-LAST:event_Btn_AlterarActionPerformed

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
       try {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            // Abre no diretorio especifico
            fc.setCurrentDirectory(new File ("./src/FotoVeiculos"));
            fc.showOpenDialog(this);
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            Txt_URL.setText(nomeDoArquivo);
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
            Panel_Logo.getWidth(),Panel_Logo.getHeight(),1));
            Panel_Logo.setIcon(iconLogo);
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void tabelaVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculosMouseClicked
        int selectedRow = tabelaVeiculos.getSelectedRow();
            if (selectedRow != -1) {
                String marcaSelecionada = (String) tabelaVeiculos.getValueAt(selectedRow, 1);
                JCBX_Marca.setSelectedItem(marcaSelecionada); // Define o valor selecionado na combobox de marcas

                String modeloSelecionado = (String) tabelaVeiculos.getValueAt(selectedRow, 2);
                JCBX_Modelo.setSelectedItem(modeloSelecionado); // Define o valor selecionado na combobox de modelos
            }

        try {
            String marcaSelecionada = (String) this.tabelaVeiculos.getValueAt(tabelaVeiculos.getSelectedRow(), 1);
            JCBX_Marca.setSelectedItem(marcaSelecionada);

            String modeloSelecionado = (String) this.tabelaVeiculos.getValueAt(tabelaVeiculos.getSelectedRow(), 2);
            JCBX_Modelo.setSelectedItem(modeloSelecionado);

            String nomeDoArquivo = (String) this.tabelaVeiculos.getValueAt(tabelaVeiculos.getSelectedRow(), 3);
            Txt_URL.setText(nomeDoArquivo);
            
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
            Panel_Logo.getWidth(),Panel_Logo.getHeight(),1));
            Panel_Logo.setIcon(iconLogo);
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_tabelaVeiculosMouseClicked

    private void JCBX_MarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCBX_MarcaFocusGained
        JCBX_Modelo.removeAllItems();
    }//GEN-LAST:event_JCBX_MarcaFocusGained

    private void JCBX_ModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCBX_ModeloFocusGained
           /* String modeloSelecionado = (String) JCBX_Modelo.getSelectedItem();
        
    try {
        Connection connection = DatabaseConnection.getConnection();
        PreparedStatement stmt = connection.prepareStatement("SELECT marcas FROM tabelademarcas INNER JOIN tabelademodelos ON tabelademarcas.id = tabelademodelos.idmarcas WHERE tabelademodelos.modelos = ?");
        stmt.setString(1, modeloSelecionado);
        ResultSet rs = stmt.executeQuery();

        
        if (rs.next()) {
            String marcaSelecionada = rs.getString("marcas");
            JCBX_Marca.setSelectedItem(marcaSelecionada);
        }

        rs.close();
        stmt.close();
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }*/
    }//GEN-LAST:event_JCBX_ModeloFocusGained

    private void JCBX_MarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCBX_MarcaFocusLost
        String marcaSelecionada = (String) JCBX_Marca.getSelectedItem();
        JCBX_Modelo.removeAllItems();
    try {
        Connection connection = DatabaseConnection.getConnection();
        PreparedStatement stmt = connection.prepareStatement("SELECT modelos FROM tabelademodelos INNER JOIN tabelademarcas ON tabelademarcas.id = tabelademodelos.idmarcas WHERE tabelademarcas.marcas = ?");
        stmt.setString(1, marcaSelecionada);
        ResultSet rs = stmt.executeQuery();

        
        List<String> modelos = new ArrayList<>();
        while (rs.next()) {
            modelos.add(rs.getString("modelos"));
        }

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(modelos.toArray(new String[0]));
        JCBX_Modelo.setModel(comboBoxModel);

        rs.close();
        stmt.close();
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_JCBX_MarcaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDosVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDosVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDosVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDosVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDosVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton Btn_Alterar;
    private javax.swing.JButton Btn_Incluir;
    private javax.swing.JComboBox<String> JCBX_Marca;
    private javax.swing.JComboBox<String> JCBX_Modelo;
    private javax.swing.JMenu MenuMarcas;
    private javax.swing.JMenu MenuModelos;
    private javax.swing.JLabel Panel_Logo;
    private javax.swing.JTextField Txt_URL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVeiculos;
    // End of variables declaration//GEN-END:variables
}
